/*
 * madana-api
 *
 * <h1>API Quickstart Guide</h1>        <p>This documentation contains a Quickstart Guide, a few <a href=\"downloads.html\">sample clients</a>  for download and information about the available  <a href=\"resources.html\">endpoints</a>  and  <a href=\"data.html\">DataTypes</a>  </p>     <p>The <a target=\"_blank\" href=\"http://madana-explorer-staging.eu-central-1.elasticbeanstalk.com/login\">  MADANA Explorer</a> can be used to verify the interactions with the API</p>           <p>Internal use only. For more information visit <a href=\"https://www.madana.io\">www.madana.io</a></p>         <br> <br>
 *
 * The version of the OpenAPI document: 0.4.12
 * 
 * Generated by: https://openapi-generator.tech
 */

use std::rc::Rc;
use std::borrow::Borrow;
#[allow(unused_imports)]
use std::option::Option;

use hyper;
use serde_json;
use futures::Future;

use super::{Error, configuration};
use super::request as __internal_request;

pub struct AuthenticationServiceApiClient<C: hyper::client::Connect> {
    configuration: Rc<configuration::Configuration<C>>,
}

impl<C: hyper::client::Connect> AuthenticationServiceApiClient<C> {
    pub fn new(configuration: Rc<configuration::Configuration<C>>) -> AuthenticationServiceApiClient<C> {
        AuthenticationServiceApiClient {
            configuration,
        }
    }
}

pub trait AuthenticationServiceApi {
    fn authenticate_application(&self, body: Option<crate::models::JsonMdnCertificate>) -> Box<dyn Future<Item = crate::models::JsonMdnToken, Error = Error<serde_json::Value>>>;
    fn authenticate_ethereum_wallet(&self, wallet: &str, body: Option<crate::models::JsonMdnOAuthToken>) -> Box<dyn Future<Item = std::path::PathBuf, Error = Error<serde_json::Value>>>;
    fn authenticate_user(&self, body: Option<crate::models::JsonMdnUserCredentials>) -> Box<dyn Future<Item = crate::models::JsonMdnToken, Error = Error<serde_json::Value>>>;
    fn authenticate_with_ethereum_challenge(&self, wallet: &str, body: Option<crate::models::JsonMdnOAuthToken>) -> Box<dyn Future<Item = std::path::PathBuf, Error = Error<serde_json::Value>>>;
    fn get_fractal_authentication_url(&self, ) -> Box<dyn Future<Item = std::path::PathBuf, Error = Error<serde_json::Value>>>;
    fn get_nonce_for_ethereum_wallet(&self, wallet: &str, authorization: Option<&str>) -> Box<dyn Future<Item = crate::models::JsonMdnToken, Error = Error<serde_json::Value>>>;
    fn get_object(&self, ) -> Box<dyn Future<Item = ::std::collections::HashMap<String, serde_json::Value>, Error = Error<serde_json::Value>>>;
    fn get_twitter_authentication_url(&self, ) -> Box<dyn Future<Item = std::path::PathBuf, Error = Error<serde_json::Value>>>;
    fn set_facebook_uid(&self, body: Option<&str>) -> Box<dyn Future<Item = std::path::PathBuf, Error = Error<serde_json::Value>>>;
    fn set_fractal_uid(&self, body: Option<&str>) -> Box<dyn Future<Item = std::path::PathBuf, Error = Error<serde_json::Value>>>;
    fn set_twitter_uid(&self, body: Option<crate::models::JsonMdnOAuthToken>) -> Box<dyn Future<Item = std::path::PathBuf, Error = Error<serde_json::Value>>>;
}

impl<C: hyper::client::Connect>AuthenticationServiceApi for AuthenticationServiceApiClient<C> {
    fn authenticate_application(&self, body: Option<crate::models::JsonMdnCertificate>) -> Box<dyn Future<Item = crate::models::JsonMdnToken, Error = Error<serde_json::Value>>> {
        let mut req = __internal_request::Request::new(hyper::Method::Post, "/authentication/application".to_string())
        ;
        req = req.with_body_param(body);

        req.execute(self.configuration.borrow())
    }

    fn authenticate_ethereum_wallet(&self, wallet: &str, body: Option<crate::models::JsonMdnOAuthToken>) -> Box<dyn Future<Item = std::path::PathBuf, Error = Error<serde_json::Value>>> {
        let mut req = __internal_request::Request::new(hyper::Method::Post, "/authentication/ethereum/{wallet}".to_string())
        ;
        req = req.with_path_param("wallet".to_string(), wallet.to_string());
        req = req.with_body_param(body);

        req.execute(self.configuration.borrow())
    }

    fn authenticate_user(&self, body: Option<crate::models::JsonMdnUserCredentials>) -> Box<dyn Future<Item = crate::models::JsonMdnToken, Error = Error<serde_json::Value>>> {
        let mut req = __internal_request::Request::new(hyper::Method::Post, "/authentication".to_string())
        ;
        req = req.with_body_param(body);

        req.execute(self.configuration.borrow())
    }

    fn authenticate_with_ethereum_challenge(&self, wallet: &str, body: Option<crate::models::JsonMdnOAuthToken>) -> Box<dyn Future<Item = std::path::PathBuf, Error = Error<serde_json::Value>>> {
        let mut req = __internal_request::Request::new(hyper::Method::Post, "/authentication/ethereum/{wallet}/challenge".to_string())
        ;
        req = req.with_path_param("wallet".to_string(), wallet.to_string());
        req = req.with_body_param(body);

        req.execute(self.configuration.borrow())
    }

    fn get_fractal_authentication_url(&self, ) -> Box<dyn Future<Item = std::path::PathBuf, Error = Error<serde_json::Value>>> {
        let mut req = __internal_request::Request::new(hyper::Method::Get, "/authentication/fractal".to_string())
        ;

        req.execute(self.configuration.borrow())
    }

    fn get_nonce_for_ethereum_wallet(&self, wallet: &str, authorization: Option<&str>) -> Box<dyn Future<Item = crate::models::JsonMdnToken, Error = Error<serde_json::Value>>> {
        let mut req = __internal_request::Request::new(hyper::Method::Get, "/authentication/ethereum/{wallet}".to_string())
        ;
        req = req.with_path_param("wallet".to_string(), wallet.to_string());
        if let Some(param_value) = authorization {
            req = req.with_header_param("Authorization".to_string(), param_value.to_string());
        }

        req.execute(self.configuration.borrow())
    }

    fn get_object(&self, ) -> Box<dyn Future<Item = ::std::collections::HashMap<String, serde_json::Value>, Error = Error<serde_json::Value>>> {
        let mut req = __internal_request::Request::new(hyper::Method::Get, "/authentication".to_string())
        ;

        req.execute(self.configuration.borrow())
    }

    fn get_twitter_authentication_url(&self, ) -> Box<dyn Future<Item = std::path::PathBuf, Error = Error<serde_json::Value>>> {
        let mut req = __internal_request::Request::new(hyper::Method::Get, "/authentication/twitter".to_string())
        ;

        req.execute(self.configuration.borrow())
    }

    fn set_facebook_uid(&self, body: Option<&str>) -> Box<dyn Future<Item = std::path::PathBuf, Error = Error<serde_json::Value>>> {
        let mut req = __internal_request::Request::new(hyper::Method::Post, "/authentication/facebook".to_string())
        ;
        req = req.with_body_param(body);

        req.execute(self.configuration.borrow())
    }

    fn set_fractal_uid(&self, body: Option<&str>) -> Box<dyn Future<Item = std::path::PathBuf, Error = Error<serde_json::Value>>> {
        let mut req = __internal_request::Request::new(hyper::Method::Post, "/authentication/fractal".to_string())
        ;
        req = req.with_body_param(body);

        req.execute(self.configuration.borrow())
    }

    fn set_twitter_uid(&self, body: Option<crate::models::JsonMdnOAuthToken>) -> Box<dyn Future<Item = std::path::PathBuf, Error = Error<serde_json::Value>>> {
        let mut req = __internal_request::Request::new(hyper::Method::Post, "/authentication/twitter".to_string())
        ;
        req = req.with_body_param(body);

        req.execute(self.configuration.borrow())
    }

}
