/*
 * madana-api
 *
 * <h1>API Quickstart Guide</h1>        <p>This documentation contains a Quickstart Guide, a few <a href=\"downloads.html\">sample clients</a>  for download and information about the available  <a href=\"resources.html\">endpoints</a>  and  <a href=\"data.html\">DataTypes</a>  </p>     <p>The <a target=\"_blank\" href=\"http://madana-explorer-staging.eu-central-1.elasticbeanstalk.com/login\">  MADANA Explorer</a> can be used to verify the interactions with the API</p>           <p>Internal use only. For more information visit <a href=\"https://www.madana.io\">www.madana.io</a></p>         <br> <br>
 *
 * The version of the OpenAPI document: 0.4.12
 * 
 * Generated by: https://openapi-generator.tech
 */

use std::rc::Rc;
use std::borrow::Borrow;
#[allow(unused_imports)]
use std::option::Option;

use hyper;
use serde_json;
use futures::Future;

use super::{Error, configuration};
use super::request as __internal_request;

pub struct CertificateServiceApiClient<C: hyper::client::Connect> {
    configuration: Rc<configuration::Configuration<C>>,
}

impl<C: hyper::client::Connect> CertificateServiceApiClient<C> {
    pub fn new(configuration: Rc<configuration::Configuration<C>>) -> CertificateServiceApiClient<C> {
        CertificateServiceApiClient {
            configuration,
        }
    }
}

pub trait CertificateServiceApi {
    fn authenticate_certificate(&self, body: Option<crate::models::JsonMdnData>) -> Box<dyn Future<Item = crate::models::JsonMdnCertificate, Error = Error<serde_json::Value>>>;
    fn get_certificate(&self, ) -> Box<dyn Future<Item = std::path::PathBuf, Error = Error<serde_json::Value>>>;
    fn get_certificate_0(&self, fingerprint: &str) -> Box<dyn Future<Item = std::path::PathBuf, Error = Error<serde_json::Value>>>;
}

impl<C: hyper::client::Connect>CertificateServiceApi for CertificateServiceApiClient<C> {
    fn authenticate_certificate(&self, body: Option<crate::models::JsonMdnData>) -> Box<dyn Future<Item = crate::models::JsonMdnCertificate, Error = Error<serde_json::Value>>> {
        let mut req = __internal_request::Request::new(hyper::Method::Post, "/certificates".to_string())
        ;
        req = req.with_body_param(body);

        req.execute(self.configuration.borrow())
    }

    fn get_certificate(&self, ) -> Box<dyn Future<Item = std::path::PathBuf, Error = Error<serde_json::Value>>> {
        let mut req = __internal_request::Request::new(hyper::Method::Get, "/certificates/root".to_string())
        ;

        req.execute(self.configuration.borrow())
    }

    fn get_certificate_0(&self, fingerprint: &str) -> Box<dyn Future<Item = std::path::PathBuf, Error = Error<serde_json::Value>>> {
        let mut req = __internal_request::Request::new(hyper::Method::Get, "/certificates/{fingerprint}".to_string())
        ;
        req = req.with_path_param("fingerprint".to_string(), fingerprint.to_string());

        req.execute(self.configuration.borrow())
    }

}
